### ISSUE TITLE
Example recovering on error

### ISSUE THREAD

**Issue by Vanuan** [voldern/elasticsearch-writable-stream#2]
It's too often that elasticsearch is too busy and can't handle the request load.
Three questions:
1. Will writable stream pause its source stream so that memory usage doesn't grow?
2. How to continue/retry piping if elastic search goes down or otherwise timeouts?
3. Are there other ways to delay/throttle piping?

**Comment by voldern** [comment]
Hi @Vanuan,

Sorry for the slow response.
1. This is handled by the underlying streams implementation if you use `.pipe()`. The exception is if you use the `flushTimeout` option the write operation triggered by the timeout will not be used as a part of the back pressure calculation. See https://nodejs.org/api/stream.html and http://maxogden.com/node-streams.html.
2. This is currently not supported, so as-is it would have to be handled on your side or added to this library.
3. You can check out one of the following modules and add it in front of this stream: https://www.npmjs.com/search?q=stream+throttle

**Comment by Vanuan** [comment]
Thanks
