### ISSUE TITLE
Indexing error messages are swallowed during bulkWrite

### ISSUE THREAD

**Issue by martoncsikos** [voldern/elasticsearch-writable-stream#4]
When the `data` returned by client.bulk [here](https://github.com/voldern/elasticsearch-writable-stream/blob/74b90f0fc139c7a6ab7bdfe9651e39bfc12cbdfd/index.js#L101) contains errors, the error is propagated with an empty message.

The reason is [this line](https://github.com/voldern/elasticsearch-writable-stream/blob/74b90f0fc139c7a6ab7bdfe9651e39bfc12cbdfd/index.js#L111).
The errors returned by `bulk` in this case are in `item.index.error` as an object.

Items with errors in the following format should not lose their error messages:

```
{
    "index": {
        "_index": "indexName",
        "_id": "recordId",
        "_type": "recordType",
        "status": 400,
        "error": {
          "type": "errorType",
          "reason": "errorReason",
          "caused_by": {
            "type": "causedType",
            "reason": "causedReason"
      }
   }
}
```

**Comment by voldern** [comment]
Sorry for the slow reply, forgot about it over summer.

I've released v2.0.1 which should fix the problem. Thank you for making the issue! :bowing_man:
